services:
  # MONAI Label enables application developers to build labeling apps in a serverless way.
  monai-docker:
    build: ./docker/monai
    ports:
      - "$MONAI_LABEL_PORT:$MONAI_LABEL_PORT"
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./src:/opt/monai/src
    env_file:
      - .env
    command: monailabel start_server -p $MONAI_LABEL_PORT --app $MONAI_LABEL_TYPE --studies $MONAI_LABEL_STUDIES --conf models $MONAI_LABEL_MODEL
    # command: tail -f /dev/null # Wait for debug mode

  # Orthanc is a virtual scanner. user: orthanc, password: orthanc.
  orthanc-docker:
    build:
      context: ./docker/orthanc
    environment:
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./docker/orthanc-data:/var/lib/orthanc/db
      # - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    expose:
      - 4242 # Dicom SCP Receiver
    ports:
      - 42893:8042 # Web access
      - 41465:4242 # Input Dicom SCP Receiver (Output is in orthanc.json : DicomModalities)

  # Postgres for orthanc
  postgres-docker:
    image: postgres:15-alpine
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
