services:
    monai-docker:
        build: ./docker/monai
        ports:
            - "$SERVER_PORT:80"
        shm_size: '2gb'
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        volumes:
            - ./src:/opt/monai/src
        environment:
            - APP_TYPE=radiology
            - APP_PATH=/opt/monai/app_radiology
            - APP_PORT=80
            - APP_TASK_NAME=Task09_Spleen
            - APP_MODEL=deepedit
        command: monailabel start_server -p 80 --app radiology --studies Task09_Spleen/imagesTr --conf models deepedit
        # command: tail -f /dev/null # Wait for debug mode

        # ports:
        #     - "$NODE_SERVER_PORT:8000"
        # restart: on-failure
        # mem_limit: 4g
        # environment:
        #     - NODE_ENV=production node app.js
        #     - MONGO_HOSTNAME=mongo-docker
        #     - MONGO_PORT=27017
        #     - MONGO_DB=$MONGO_INITDB_DATABASE
        #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
        #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
        #     - NODE_SERVER_PORT=$NODE_SERVER_PORT
        #     - NODE_SERVER_URL=$NODE_SERVER_URL
        #     - APPLICATION_ADMIN_PASSWORD=$APPLICATION_ADMIN_PASSWORD
        #     - EXPRESS_SESSION_SECRET=$EXPRESS_SESSION_SECRET
        # volumes:
        #     - /opt/monai
        #     - ./client:/home/node/app/client
        #     - /home/node/app/server/node_modules # A hack to not override node_modules
        #     - /home/node/app/client/node_modules
        #     - /home/node/app/client/build
        # depends_on:
        #     - mongo-docker
        # command: bash startNode.sh
