services:
    monai-docker:
        build: ./docker/monai
        ports:
            - "$SERVER_PORT:80"
        shm_size: '2gb'
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        volumes:
            - ./src:/opt/monai/src
        environment:
            - APP_TYPE=radiology
            - APP_PATH=/opt/monai/app_radiology
            - APP_PORT=80
            - APP_TASK_NAME=Task09_Spleen
            - APP_MODEL=deepedit
        command: monailabel start_server -p 80 --app radiology --studies Task09_Spleen/imagesTr --conf models deepedit
        # command: tail -f /dev/null # Wait for debug mode
